In [1]:
import statistics as stat

In [3]:
stat.mean([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

185.3

In [5]:
stat.median([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

169.0

In [6]:
stat.median_low([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

160

In [7]:
stat.median_high([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

178

In [8]:
stat.mode([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

120

In [9]:
stat.harmonic_mean([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

164.72213877403078

In [10]:
stat.stdev([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

66.8781588831004

In [11]:
stat.variance([100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,
248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204])

4472.68813559322

In [2]:
import numpy

In [3]:
speed =[100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105] 

In [4]:
speed1 =[248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204]

In [5]:
x = numpy.mean(speed)
y = numpy.mean(speed1)

In [6]:
print(x)
print(y)

131.2
239.4


In [17]:
print(x)

239.4


In [18]:
print(y)

239.4


In [19]:
speed =[100,124,132,138,132,112,142,140,108,130,130,148,178,140,120,129,120,160,138,120,110,180,150,140,110,130,120,130,120,105,248,255,207,223,288,160,226,394,233,315,246,244,270,195,240,196,211,234,236,244,254,325,126,313,211,262,215,214,193,204] 

In [20]:
x=numpy.mean(speed)

In [21]:
print(x)

185.3


In [7]:
random_speed = numpy.random.randint(low=100,high=500,size=20) 

In [8]:
print(random_speed)

[251 433 400 193 436 346 395 219 235 155 289 190 291 496 268 342 414 305
 238 455]


In [9]:
random_speed = numpy.random.randint(low=100,high=500,size=(5,5)) 

In [10]:
print(random_speed)

[[374 488 111 467 435]
 [169 157 457 444 321]
 [412 341 247 385 112]
 [112 271 325 290 262]
 [282 281 158 362 447]]
